# Generated by Django 4.2.1 on 2023-06-03 07:31

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0002_alter_useraccount_is_staff'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='summarises',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(170)]),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(upload_to='D:\\Commerece/containers/authors_image'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.CreateModel(
            name='WatchListCategories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blogs_app.categories')),
            ],
        ),
    ]
