# Generated by Django 4.2.1 on 2023-06-03 07:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0003_alter_articles_summarises_alter_useraccount_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='watchlistcategories',
            name='user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='watchlist_categories', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='watchlistcategories',
            name='category',
        ),
        migrations.AddField(
            model_name='watchlistcategories',
            name='category',
            field=models.ManyToManyField(related_name='watch_categories', to='blogs_app.categories'),
        ),
    ]
