# Generated by Django 4.2.1 on 2023-06-04 09:32

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0004_watchlistcategories_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(blank=True, max_length=255, null=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
