# Generated by Django 4.2.1 on 2023-06-04 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0005_alter_useraccount_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='D:\\Commerece\\containers//images/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(upload_to='D:\\Commerece\\containers//authors_image'),
        ),
    ]
