# Generated by Django 4.2.1 on 2023-06-04 16:52

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0007_alter_useraccount_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='', verbose_name='D:\\Commerece\\containers/images//images/'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(default='undecided', unique=True),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(upload_to='D:\\Commerece\\containers/images//authors_image'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='username',
            field=models.CharField(max_length=255, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()]),
        ),
    ]
