# Generated by Django 4.2.1 on 2023-06-06 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs_app', '0008_alter_articles_image_alter_categories_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='image',
            field=models.ImageField(upload_to='D:\\Commerece\\containers/images//images/'),
        ),
        migrations.AlterField(
            model_name='useraccount',
            name='image',
            field=models.ImageField(upload_to='D:\\Commerece\\containers/images//authors_image/'),
        ),
    ]
